#ifndef __TYPES_H__
#define __TYPES_H__

typedef char _bool;

#define MAP_WIDTH 100
#define MAP_HEIGHT 100


#define PREDATOR_INIT_CNT 20
#define PREY_INIT_CNT 100


#define PREDATOR_BABY_DELAY -2
#define PREDATOR_MARRY_DELAY -5
#define PREDATOR_MARRY_PUNISHMENT 4

#define PREDATOR_LIFE_SPAN 100
#define PREDATOR_SIGHT 5

#define PREDATOR_HEREDITY_SEED 6
#define PREDATOR_MUTATION_SEED 30
#define PREDATOR_ODD_HEREDITY_SEED 50

#define PREDATOR_GENE_STORE_SIZE 50

#define PREDATOR_PROBABILITY_SEED 1000
#define PREDATOR_MUTATION_PROBABILITY 10 /* 10/SEED */
#define PREDATOR_ODD_HEREDITY_PROBABILITY 1 /* 1/SEED */


#define DIRECT_CNT 4
#define DIRECT_UP 0
#define DIRECT_DOWN 1
#define DIRECT_LEFT 2
#define DIRECT_RIGHT 3


#define CODE_BLANK 0
#define CODE_PREDAT0R 1
#define CODE_PREY 2

#endif